export const DEFAULT_LATEX_SUITE_SNIPPETS_RAW_STRING = `[
    // Math mode
	{trigger: "mk", replacement: "$$0$", options: "tA"},
	{trigger: "dm", replacement: "$$\\n$0\\n$$", options: "tAw"},
	{trigger: "beg", replacement: "\\\\begin{$0}\\n$1\\n\\\\end{$0}", options: "mA"},

    // Greek letters
	{trigger: "@a", replacement: "\\\\alpha", options: "mA"},
	{trigger: "@b", replacement: "\\\\beta", options: "mA"},
	{trigger: "@g", replacement: "\\\\gamma", options: "mA"},
	{trigger: "@G", replacement: "\\\\Gamma", options: "mA"},
	{trigger: "@d", replacement: "\\\\delta", options: "mA"},
	{trigger: "@D", replacement: "\\\\Delta", options: "mA"},
	{trigger: "@e", replacement: "\\\\epsilon", options: "mA"},
	{trigger: ":e", replacement: "\\\\varepsilon", options: "mA"},
	{trigger: "@z", replacement: "\\\\zeta", options: "mA"},
	{trigger: "@t", replacement: "\\\\theta", options: "mA"},
	{trigger: "@T", replacement: "\\\\Theta", options: "mA"},
	{trigger: ":t", replacement: "\\\\vartheta", options: "mA"},
	{trigger: "@i", replacement: "\\\\iota", options: "mA"},
	{trigger: "@k", replacement: "\\\\kappa", options: "mA"},
	{trigger: "@l", replacement: "\\\\lambda", options: "mA"},
	{trigger: "@L", replacement: "\\\\Lambda", options: "mA"},
	{trigger: "@s", replacement: "\\\\sigma", options: "mA"},
	{trigger: "@S", replacement: "\\\\Sigma", options: "mA"},
	{trigger: "@u", replacement: "\\\\upsilon", options: "mA"},
	{trigger: "@U", replacement: "\\\\Upsilon", options: "mA"},
	{trigger: "@o", replacement: "\\\\omega", options: "mA"},
	{trigger: "@O", replacement: "\\\\Omega", options: "mA"},
	{trigger: "ome", replacement: "\\\\omega", options: "mA"},
	{trigger: "Ome", replacement: "\\\\Omega", options: "mA"},

    // Text environment
    {trigger: "text", replacement: "\\\\text{$0}$1", options: "mA"},
    {trigger: "\\"", replacement: "\\\\text{$0}$1", options: "mA"},

    // Basic operations
    {trigger: "sr", replacement: "^{2}", options: "mA"},
	{trigger: "cb", replacement: "^{3}", options: "mA"},
	{trigger: "rd", replacement: "^{$0}$1", options: "mA"},
	{trigger: "_", replacement: "_{$0}$1", options: "mA"},
	{trigger: "sts", replacement: "_\\\\text{$0}", options: "mA"},
	{trigger: "sq", replacement: "\\\\sqrt{ $0 }$1", options: "mA"},
	{trigger: "//", replacement: "\\\\frac{$0}{$1}$2", options: "mA"},
	{trigger: "ee", replacement: "e^{ $0 }$1", options: "mA"},
    {trigger: "invs", replacement: "^{-1}", options: "mA"},
    {trigger: /([A-Za-z])(\\d)/, replacement: "[[0]]_{[[1]]}", options: "rmA", description: "Auto letter subscript", priority: -1},

    {trigger: /([^\\\\])(exp|log|ln)/, replacement: "[[0]]\\\\[[1]]", options: "rmA"},
    {trigger: "conj", replacement: "^{*}", options: "mA"},
    {trigger: "Re", replacement: "\\\\mathrm{Re}", options: "mA"},
	{trigger: "Im", replacement: "\\\\mathrm{Im}", options: "mA"},
    {trigger: "bf", replacement: "\\\\mathbf{$0}", options: "mA"},
	{trigger: "rm", replacement: "\\\\mathrm{$0}$1", options: "mA"},

    // Linear algebra
    {trigger: /([^\\\\])(det)/, replacement: "[[0]]\\\\[[1]]", options: "rmA"},
    {trigger: "trace", replacement: "\\\\mathrm{Tr}", options: "mA"},

    // More operations
	{trigger: "([a-zA-Z])hat", replacement: "\\\\hat{[[0]]}", options: "rmA"},
    {trigger: "([a-zA-Z])bar", replacement: "\\\\bar{[[0]]}", options: "rmA"},
	{trigger: "([a-zA-Z])dot", replacement: "\\\\dot{[[0]]}", options: "rmA", priority: -1},
	{trigger: "([a-zA-Z])ddot", replacement: "\\\\ddot{[[0]]}", options: "rmA", priority: 1},
	{trigger: "([a-zA-Z])tilde", replacement: "\\\\tilde{[[0]]}", options: "rmA"},
	{trigger: "([a-zA-Z])und", replacement: "\\\\underline{[[0]]}", options: "rmA"},
	{trigger: "([a-zA-Z])vec", replacement: "\\\\vec{[[0]]}", options: "rmA"},
    {trigger: "([a-zA-Z]),\\\\.", replacement: "\\\\mathbf{[[0]]}", options: "rmA"},
	{trigger: "([a-zA-Z])\\\\.,", replacement: "\\\\mathbf{[[0]]}", options: "rmA"},
	{trigger: "\\\\(\${GREEK}),\\\\.", replacement: "\\\\boldsymbol{\\\\[[0]]}", options: "rmA"},
	{trigger: "\\\\(\${GREEK})\\\\.,", replacement: "\\\\boldsymbol{\\\\[[0]]}", options: "rmA"},

	{trigger: "hat", replacement: "\\\\hat{$0}$1", options: "mA"},
    {trigger: "bar", replacement: "\\\\bar{$0}$1", options: "mA"},
	{trigger: "dot", replacement: "\\\\dot{$0}$1", options: "mA", priority: -1},
	{trigger: "ddot", replacement: "\\\\ddot{$0}$1", options: "mA"},
	{trigger: "cdot", replacement: "\\\\cdot", options: "mA"},
	{trigger: "tilde", replacement: "\\\\tilde{$0}$1", options: "mA"},
	{trigger: "und", replacement: "\\\\underline{$0}$1", options: "mA"},
	{trigger: "vec", replacement: "\\\\vec{$0}$1", options: "mA"},
    {
        trigger: "pmod",
        replacement: "\\\\pmod{\${0:n}}\$1",
        options: "mA",
        description: "Parenthesized modulo (\\\\pmod{n})",
    },

    // More auto letter subscript
    {trigger: /([A-Za-z])_(\\d\\d)/, replacement: "[[0]]_{[[1]]}", options: "rmA"},
	{trigger: /\\\\hat{([A-Za-z])}(\\d)/, replacement: "\\\\hat{[[0]]}_{[[1]]}", options: "rmA"},
	{trigger: /\\\\vec{([A-Za-z])}(\\d)/, replacement: "\\\\vec{[[0]]}_{[[1]]}", options: "rmA"},
	{trigger: /\\\\mathbf{([A-Za-z])}(\\d)/, replacement: "\\\\mathbf{[[0]]}_{[[1]]}", options: "rmA"},

    {trigger: "xnn", replacement: "x_{n}", options: "mA"},
	{trigger: "\\\\xii", replacement: "x_{i}", options: "mA", priority: 1},
	{trigger: "xjj", replacement: "x_{j}", options: "mA"},
	{trigger: "xp1", replacement: "x_{n+1}", options: "mA"},
	{trigger: "ynn", replacement: "y_{n}", options: "mA"},
	{trigger: "yii", replacement: "y_{i}", options: "mA"},
	{trigger: "yjj", replacement: "y_{j}", options: "mA"},

    // Symbols
    {trigger: "ooo", replacement: "\\\\infty", options: "mA"},
	{trigger: "sum", replacement: "\\\\sum", options: "mA"},
	{trigger: "prod", replacement: "\\\\prod", options: "mA"},
	{trigger: "\\\\sum", replacement: "\\\\sum_{\${0:i}=\${1:1}}^{\${2:N}} \$3", options: "m"},
	{trigger: "\\\\prod", replacement: "\\\\prod_{\${0:i}=\${1:1}}^{\${2:N}} \$3", options: "m"},
    {trigger: "lim", replacement: "\\\\lim_{ \${0:n} \\\\to \${1:\\\\infty} } \$2", options: "mA"},
    {trigger: "+-", replacement: "\\\\pm", options: "mA"},
	{trigger: "-+", replacement: "\\\\mp", options: "mA"},
    {trigger: "...", replacement: "\\\\dots", options: "mA"},
    {trigger: "nabl", replacement: "\\\\nabla", options: "mA"},
	{trigger: "xx", replacement: "\\\\times", options: "mA"},
    {trigger: "**", replacement: "\\\\cdot", options: "mA"},
    {trigger: "para", replacement: "\\\\parallel", options: "mA"},

	{trigger: "===", replacement: "\\\\equiv", options: "mA"},
    {trigger: "!=", replacement: "\\\\neq", options: "mA"},
	{trigger: ">=", replacement: "\\\\geq", options: "mA"},
	{trigger: "<=", replacement: "\\\\leq", options: "mA"},
	{trigger: ">>", replacement: "\\\\gg", options: "mA"},
	{trigger: "<<", replacement: "\\\\ll", options: "mA"},
	{trigger: "simm", replacement: "\\\\sim", options: "mA"},
	{trigger: "sim=", replacement: "\\\\simeq", options: "mA"},
    {trigger: "prop", replacement: "\\\\propto", options: "mA"},

    {trigger: "<->", replacement: "\\\\leftrightarrow ", options: "mA"},
	{trigger: "->", replacement: "\\\\to", options: "mA"},
	{trigger: "!>", replacement: "\\\\mapsto", options: "mA"},
    {trigger: "=>", replacement: "\\\\implies", options: "mA"},
	{trigger: "=<-", replacement: "\\\\impliedby", options: "mA"},

	{trigger: "and", replacement: "\\\\cap", options: "mA"},
	{trigger: "orr", replacement: "\\\\cup", options: "mA"},
	{trigger: "inn", replacement: "\\\\in", options: "mA"},
	{trigger: "notin", replacement: "\\\\not\\\\in", options: "mA"},
    {trigger: "sub=", replacement: "\\\\subseteq", options: "mA"},
    {trigger: "sup=", replacement: "\\\\supseteq", options: "mA"},
	{trigger: "eset", replacement: "\\\\emptyset", options: "mA"},
	{trigger: "set", replacement: "\\\\{ \$0 \\\\}\$1", options: "mA"},

	{trigger: "LL", replacement: "\\\\mathcal{L}", options: "mA"},
	{trigger: "HH", replacement: "\\\\mathcal{H}", options: "mA"},
	{trigger: "CC", replacement: "\\\\mathbb{C}", options: "mA"},
	{trigger: "RR", replacement: "\\\\mathbb{R}", options: "mA"},
	{trigger: "ZZ", replacement: "\\\\mathbb{Z}", options: "mA"},
	{trigger: "NN", replacement: "\\\\mathbb{N}", options: "mA"},

	{trigger: "([^\\\\\\\\])(\${GREEK})", replacement: "[[0]]\\\\[[1]]", options: "rmA", description: "Add backslash before Greek letters"},
	{trigger: "([^\\\\\\\\])(\${SYMBOL})", replacement: "[[0]]\\\\[[1]]", options: "rmA", description: "Add backslash before symbols"},

	{trigger: "\\\\(\${GREEK}|\${SYMBOL}|\${MORE_SYMBOLS})([A-Za-z])", replacement: "\\\\[[0]] [[1]]", options: "rmA"},
	{trigger: "\\\\(\${GREEK}|\${SYMBOL}) sr", replacement: "\\\\[[0]]^{2}", options: "rmA"},
	{trigger: "\\\\(\${GREEK}|\${SYMBOL}) cb", replacement: "\\\\[[0]]^{3}", options: "rmA"},
	{trigger: "\\\\(\${GREEK}|\${SYMBOL}) rd", replacement: "\\\\[[0]]^{\$0}\$1", options: "rmA"},
	{trigger: "\\\\(\${GREEK}) hat", replacement: "\\\\hat{\\\\[[0]]}", options: "rmA"},
	{trigger: "\\\\(\${GREEK}) dot", replacement: "\\\\dot{\\\\[[0]]}", options: "rmA"},
	{trigger: "\\\\(\${GREEK}) bar", replacement: "\\\\bar{\\\\[[0]]}", options: "rmA"},
	{trigger: "\\\\(\${GREEK}) vec", replacement: "\\\\vec{\\\\[[0]]}", options: "rmA"},
	{trigger: "\\\\(\${GREEK}) tilde", replacement: "\\\\tilde{\\\\[[0]]}", options: "rmA"},
	{trigger: "\\\\(\${GREEK}) und", replacement: "\\\\underline{\\\\[[0]]}", options: "rmA"},

    // Derivatives and integrals
    {trigger: "par", replacement: "\\\\frac{ \\\\partial \${0:y} }{ \\\\partial \${1:x} } \$2", options: "m"},
    {trigger: /pa([A-Za-z])([A-Za-z])/, replacement: "\\\\frac{ \\\\partial [[0]] }{ \\\\partial [[1]] } ", options: "rm"},
    {trigger: "ddt", replacement: "\\\\frac{d}{dt} ", options: "mA"},

    {trigger: /([^\\\\])int/, replacement: "[[0]]\\\\int", options: "mA", priority: -1},
    {trigger: "\\\\int", replacement: "\\\\int \$0 \\\\, d\${1:x} \$2", options: "m"},
    {trigger: "dint", replacement: "\\\\int_{\${0:0}}^{\${1:1}} \$2 \\\\, d\${3:x} \$4", options: "mA"},
    {trigger: "oint", replacement: "\\\\oint", options: "mA"},
	{trigger: "iint", replacement: "\\\\iint", options: "mA"},
    {trigger: "iiint", replacement: "\\\\iiint", options: "mA"},
    {trigger: "oinf", replacement: "\\\\int_{0}^{\\\\infty} \$0 \\\\, d\${1:x} \$2", options: "mA"},
	{trigger: "infi", replacement: "\\\\int_{-\\\\infty}^{\\\\infty} \$0 \\\\, d\${1:x} \$2", options: "mA"},

    // Trigonometry
    {trigger: /([^\\\\])(arcsin|sin|arccos|cos|arctan|tan|csc|sec|cot)/, replacement: "[[0]]\\\\[[1]]", options: "rmA"},
    {trigger: /\\\\(arcsin|sin|arccos|cos|arctan|tan|csc|sec|cot)([A-Za-gi-z])/, replacement: "\\\\[[0]] [[1]]", options: "rmA"},
    {trigger: /\\\\(sinh|cosh|tanh|coth)([A-Za-z])/, replacement: "\\\\[[0]] [[1]]", options: "rmA"},

    // Visual operations
	{trigger: "U", replacement: "\\\\underbrace{ \${VISUAL} }_{ \$0 }", options: "mA"},
	{trigger: "O", replacement: "\\\\overbrace{ \${VISUAL} }^{\$0 }", options: "mA"},
	{trigger: "B", replacement: "\\\\underset{ \$0 }{ \${VISUAL} }", options: "mA"},
	{trigger: "C", replacement: "\\\\cancel{ \${VISUAL} }", options: "mA"},
	{trigger: "K", replacement: "\\\\cancelto{ \$0 }{ \${VISUAL} }", options: "mA"},
	{trigger: "S", replacement: "\\\\sqrt{ \${VISUAL} }", options: "mA"},

    // Quantum mechanics & Physics
    {trigger: "dag", replacement: "^{\\\\dagger}", options: "mA"},
	{trigger: "o+", replacement: "\\\\oplus ", options: "mA"},
	{trigger: "ox", replacement: "\\\\otimes ", options: "mA"},
    {trigger: "bra", replacement: "\\\\bra{\$0} \$1", options: "mA"},
	{trigger: "ket", replacement: "\\\\ket{\$0} \$1", options: "mA"},
	{trigger: "brk", replacement: "\\\\braket{ \$0 | \$1 } \$2", options: "mA"},

    // Environments
    {trigger: /([pbBvV]mat)/, replacement: "\\\\begin{[[0]]rix}\\n\$0\\n\\\\end{[[0]]rix}", options: "rMA"},
    {trigger: /(matrix|cases|align|array)/, replacement: "\\\\begin{[[0]]}\\n\$0\\n\\\\end{[[0]]}", options: "rMA"},

    // Brackets
	{trigger: "avg", replacement: "\\\\langle \$0 \\\\rangle \$1", options: "mA"},
	{trigger: "norm", replacement: "\\\\lvert \$0 \\\\rvert \$1", options: "mA", priority: 1},
	{trigger: "Norm", replacement: "\\\\lVert \$0 \\\\rVert \$1", options: "mA", priority: 1},
	{trigger: "ceil", replacement: "\\\\lceil \$0 \\\\rceil \$1", options: "mA"},
	{trigger: "floor", replacement: "\\\\floor \$0 \\\\rfloor \$1", options: "mA"},
	{trigger: "mod", replacement: "|\$0|\$1", options: "mA"},
	{trigger: "(", replacement: "(\${VISUAL})", options: "mA"},
	{trigger: "[", replacement: "[\${VISUAL}]", options: "mA"},
	{trigger: "{", replacement: "{\${VISUAL}}", options: "mA"},
	{trigger: "lr(", replacement: "\\\\left( \$0 \\\\right) \$1", options: "mA"},
	{trigger: "lr{", replacement: "\\\\left\\\\{ \$0 \\\\right\\\\} \$1", options: "mA"},
	{trigger: "lr[", replacement: "\\\\left[ \$0 \\\\right] \$1", options: "mA"},
	{trigger: "lr|", replacement: "\\\\left| \$0 \\\\right| \$1", options: "mA"},
	{trigger: "lra", replacement: "\\\\left< \$0 \\\\right> \$1", options: "mA"}
]`;
