export interface RawSnippet {
  trigger: string;
  replacement: string;
  options?: string; // "m" = math mode only, "t" = text mode only, "A" = auto-expand, "r" = regex
  description?: string;
  priority?: number;
}

export const DEFAULT_LATEX_SUITE_SNIPPETS: RawSnippet[] = [
  // ── Mode Toggles ──
  { trigger: "mk", replacement: "$$0$", options: "tA", description: "Inline math environment" },
  { trigger: "dm", replacement: "$$\n$0\n$$", options: "tA", description: "Display math environment" },
  { trigger: "beg", replacement: "\\\\begin{$0}\n$1\n\\\\end{$0}", options: "mA", description: "Begin environment" },

  // ── Greek Letters ──
  { trigger: "@a", replacement: "\\\\alpha", options: "mA" },
  { trigger: "@b", replacement: "\\\\beta", options: "mA" },
  { trigger: "@g", replacement: "\\\\gamma", options: "mA" },
  { trigger: "@G", replacement: "\\\\Gamma", options: "mA" },
  { trigger: "@d", replacement: "\\\\delta", options: "mA" },
  { trigger: "@D", replacement: "\\\\Delta", options: "mA" },
  { trigger: "@e", replacement: "\\\\epsilon", options: "mA" },
  { trigger: ":e", replacement: "\\\\varepsilon", options: "mA" },
  { trigger: "@z", replacement: "\\\\zeta", options: "mA" },
  { trigger: "@t", replacement: "\\\\theta", options: "mA" },
  { trigger: "@T", replacement: "\\\\Theta", options: "mA" },
  { trigger: ":t", replacement: "\\\\vartheta", options: "mA" },
  { trigger: "@i", replacement: "\\\\iota", options: "mA" },
  { trigger: "@k", replacement: "\\\\kappa", options: "mA" },
  { trigger: "@l", replacement: "\\\\lambda", options: "mA" },
  { trigger: "@L", replacement: "\\\\Lambda", options: "mA" },
  { trigger: "@s", replacement: "\\\\sigma", options: "mA" },
  { trigger: "@S", replacement: "\\\\Sigma", options: "mA" },
  { trigger: "@u", replacement: "\\\\upsilon", options: "mA" },
  { trigger: "@U", replacement: "\\\\Upsilon", options: "mA" },
  { trigger: "@o", replacement: "\\\\omega", options: "mA" },
  { trigger: "@O", replacement: "\\\\Omega", options: "mA" },
  { trigger: "ome", replacement: "\\\\omega", options: "mA" },
  { trigger: "Ome", replacement: "\\\\Omega", options: "mA" },
  { trigger: "al", replacement: "\\\\alpha", options: "mA" },
  { trigger: "be", replacement: "\\\\beta", options: "mA" },
  { trigger: "ga", replacement: "\\\\gamma", options: "mA" },
  { trigger: "de", replacement: "\\\\delta", options: "mA" },
  { trigger: "ep", replacement: "\\\\epsilon", options: "mA" },
  { trigger: "ze", replacement: "\\\\zeta", options: "mA" },
  { trigger: "et", replacement: "\\\\eta", options: "mA" },
  { trigger: "th", replacement: "\\\\theta", options: "mA" },
  { trigger: "io", replacement: "\\\\iota", options: "mA" },
  { trigger: "ka", replacement: "\\\\kappa", options: "mA" },
  { trigger: "la", replacement: "\\\\lambda", options: "mA" },
  { trigger: "mu", replacement: "\\\\mu", options: "mA" },
  { trigger: "nu", replacement: "\\\\nu", options: "mA" },
  { trigger: "xi", replacement: "\\\\xi", options: "mA" },
  { trigger: "pi", replacement: "\\\\pi", options: "mA" },
  { trigger: "ro", replacement: "\\\\rho", options: "mA" },
  { trigger: "si", replacement: "\\\\sigma", options: "mA" },
  { trigger: "ta", replacement: "\\\\tau", options: "mA" },
  { trigger: "ph", replacement: "\\\\phi", options: "mA" },
  { trigger: "chi", replacement: "\\\\chi", options: "mA" },
  { trigger: "ps", replacement: "\\\\psi", options: "mA" },
  { trigger: "om", replacement: "\\\\omega", options: "mA" },

  // ── Text & Fonts ──
  { trigger: "text", replacement: "\\\\text{$0}$1", options: "mA" },
  { trigger: "bf", replacement: "\\\\mathbf{$0}", options: "mA" },
  { trigger: "rm", replacement: "\\\\mathrm{$0}$1", options: "mA" },
  { trigger: "tt", replacement: "\\\\text{$0}$1", options: "mA" },

  // ── Basic Operations & Sub/Superscripts ──
  { trigger: "sr", replacement: "^{2}", options: "mA" },
  { trigger: "cb", replacement: "^{3}", options: "mA" },
  { trigger: "rd", replacement: "^{$0}$1", options: "mA" },
  { trigger: "_", replacement: "_{$0}$1", options: "mA" },
  { trigger: "sts", replacement: "_\\\\text{$0}", options: "mA" },
  { trigger: "sq", replacement: "\\\\sqrt{ $0 }$1", options: "mA" },
  { trigger: "fra", replacement: "\\\\frac{$0}{$1}$2", options: "mA" },
  { trigger: "//", replacement: "\\\\frac{$0}{$1}$2", options: "mA" },
  { trigger: "ee", replacement: "e^{ $0 }$1", options: "mA" },
  { trigger: "invs", replacement: "^{-1}", options: "mA" },
  { trigger: "conj", replacement: "^{*}", options: "mA" },
  { trigger: "Re", replacement: "\\\\mathrm{Re}", options: "mA" },
  { trigger: "Im", replacement: "\\\\mathrm{Im}", options: "mA" },
  { trigger: "trace", replacement: "\\\\mathrm{Tr}", options: "mA" },

  // ── Accents ──
  { trigger: "hat", replacement: "\\\\hat{$0}$1", options: "mA" },
  { trigger: "bar", replacement: "\\\\bar{$0}$1", options: "mA" },
  { trigger: "dot", replacement: "\\\\dot{$0}$1", options: "mA", priority: -1 },
  { trigger: "ddot", replacement: "\\\\ddot{$0}$1", options: "mA" },
  { trigger: "cdot", replacement: "\\\\cdot", options: "mA" },
  { trigger: "tilde", replacement: "\\\\tilde{$0}$1", options: "mA" },
  { trigger: "und", replacement: "\\\\underline{$0}$1", options: "mA" },
  { trigger: "vec", replacement: "\\\\vec{$0}$1", options: "mA" },
  { trigger: "pmod", replacement: "\\\\pmod{${0:n}}$1", options: "mA" },

  // ── Subscript variables ──
  { trigger: "xnn", replacement: "x_{n}", options: "mA" },
  { trigger: "xii", replacement: "x_{i}", options: "mA" },
  { trigger: "xjj", replacement: "x_{j}", options: "mA" },
  { trigger: "xp1", replacement: "x_{n+1}", options: "mA" },
  { trigger: "ynn", replacement: "y_{n}", options: "mA" },
  { trigger: "yii", replacement: "y_{i}", options: "mA" },
  { trigger: "yjj", replacement: "y_{j}", options: "mA" },

  // ── Symbols ──
  { trigger: "ooo", replacement: "\\\\infty", options: "mA" },
  { trigger: "oo", replacement: "\\\\infty", options: "mA" },
  { trigger: "sum", replacement: "\\\\sum_{${0:i=1}}^{${1:n}} $2", options: "mA" },
  { trigger: "prod", replacement: "\\\\prod_{${0:i=1}}^{${1:n}} $2", options: "mA" },
  { trigger: "lim", replacement: "\\\\lim_{ ${0:n} \\\\to ${1:\\\\infty} } $2", options: "mA" },
  { trigger: "+-", replacement: "\\\\pm", options: "mA" },
  { trigger: "-+", replacement: "\\\\mp", options: "mA" },
  { trigger: "...", replacement: "\\\\dots", options: "mA" },
  { trigger: "nabl", replacement: "\\\\nabla", options: "mA" },
  { trigger: "grad", replacement: "\\\\nabla", options: "mA" },
  { trigger: "xx", replacement: "\\\\times", options: "mA" },
  { trigger: "**", replacement: "\\\\cdot", options: "mA" },
  { trigger: "para", replacement: "\\\\parallel", options: "mA" },
  { trigger: "===", replacement: "\\\\equiv", options: "mA" },
  { trigger: "!=", replacement: "\\\\neq", options: "mA" },
  { trigger: ">=", replacement: "\\\\geq", options: "mA" },
  { trigger: "<=", replacement: "\\\\leq", options: "mA" },
  { trigger: ">>", replacement: "\\\\gg", options: "mA" },
  { trigger: "<<", replacement: "\\\\ll", options: "mA" },
  { trigger: "simm", replacement: "\\\\sim", options: "mA" },
  { trigger: "sim=", replacement: "\\\\simeq", options: "mA" },
  { trigger: "prop", replacement: "\\\\propto", options: "mA" },

  // ── Arrows & Relations ──
  { trigger: "<->", replacement: "\\\\leftrightarrow ", options: "mA" },
  { trigger: "->", replacement: "\\\\to", options: "mA" },
  { trigger: "!>", replacement: "\\\\mapsto", options: "mA" },
  { trigger: "=>", replacement: "\\\\implies", options: "mA" },
  { trigger: "=<", replacement: "\\\\impliedby", options: "mA" },
  { trigger: "and", replacement: "\\\\cap", options: "mA" },
  { trigger: "orr", replacement: "\\\\cup", options: "mA" },
  { trigger: "inn", replacement: "\\\\in", options: "mA" },
  { trigger: "notin", replacement: "\\\\not\\\\in", options: "mA" },
  { trigger: "sub=", replacement: "\\\\subseteq", options: "mA" },
  { trigger: "sup=", replacement: "\\\\supseteq", options: "mA" },
  { trigger: "eset", replacement: "\\\\emptyset", options: "mA" },
  { trigger: "set", replacement: "\\\\{ $0 \\\\}$1", options: "mA" },

  // ── Blackboard & Calligraphic ──
  { trigger: "LL", replacement: "\\\\mathcal{L}", options: "mA" },
  { trigger: "HH", replacement: "\\\\mathcal{H}", options: "mA" },
  { trigger: "CC", replacement: "\\\\mathbb{C}", options: "mA" },
  { trigger: "RR", replacement: "\\\\mathbb{R}", options: "mA" },
  { trigger: "ZZ", replacement: "\\\\mathbb{Z}", options: "mA" },
  { trigger: "NN", replacement: "\\\\mathbb{N}", options: "mA" },

  // ── Calculus & Integrals ──
  { trigger: "par", replacement: "\\\\frac{ \\\\partial ${0:y} }{ \\\\partial ${1:x} } $2", options: "mA" },
  { trigger: "ddt", replacement: "\\\\frac{d}{dt} ", options: "mA" },
  { trigger: "ddx", replacement: "\\\\frac{d $0}{d $1} $2", options: "mA" },
  { trigger: "int", replacement: "\\\\int $0 \\\\, d${1:x} $2", options: "mA" },
  { trigger: "dint", replacement: "\\\\int_{${0:0}}^{${1:1}} $2 \\\\, d${3:x} $4", options: "mA" },
  { trigger: "oint", replacement: "\\\\oint", options: "mA" },
  { trigger: "iint", replacement: "\\\\iint", options: "mA" },
  { trigger: "iiint", replacement: "\\\\iiint", options: "mA" },
  { trigger: "oinf", replacement: "\\\\int_{0}^{\\\\infty} $0 \\\\, d${1:x} $2", options: "mA" },
  { trigger: "infi", replacement: "\\\\int_{-\\\\infty}^{\\\\infty} $0 \\\\, d${1:x} $2", options: "mA" },

  // ── Physics & QM ──
  { trigger: "kbt", replacement: "k_{B}T", options: "mA" },
  { trigger: "msun", replacement: "M_{\\\\odot}", options: "mA" },
  { trigger: "dag", replacement: "^{\\\\dagger}", options: "mA" },
  { trigger: "o+", replacement: "\\\\oplus ", options: "mA" },
  { trigger: "ox", replacement: "\\\\otimes ", options: "mA" },
  { trigger: "bra", replacement: "\\\\bra{$0} $1", options: "mA" },
  { trigger: "ket", replacement: "\\\\ket{$0} $1", options: "mA" },
  { trigger: "brk", replacement: "\\\\braket{ $0 | $1 } $2", options: "mA" },

  // ── Environments (pmat, bmat, vmat, matrix, cases, align) ──
  { trigger: "pmat", replacement: "\\\\begin{pmatrix}\n$0\n\\\\end{pmatrix}", options: "mA" },
  { trigger: "bmat", replacement: "\\\\begin{bmatrix}\n$0\n\\\\end{bmatrix}", options: "mA" },
  { trigger: "vmat", replacement: "\\\\begin{vmatrix}\n$0\n\\\\end{vmatrix}", options: "mA" },
  { trigger: "cases", replacement: "\\\\begin{cases}\n$0\n\\\\end{cases}", options: "mA" },
  { trigger: "align", replacement: "\\\\begin{align}\n$0\n\\\\end{align}", options: "mA" },

  // ── Brackets & Wrappers ──
  { trigger: "avg", replacement: "\\\\langle $0 \\\\rangle $1", options: "mA" },
  { trigger: "norm", replacement: "\\\\lvert $0 \\\\rvert $1", options: "mA" },
  { trigger: "Norm", replacement: "\\\\lVert $0 \\\\rVert $1", options: "mA" },
  { trigger: "ceil", replacement: "\\\\lceil $0 \\\\rceil $1", options: "mA" },
  { trigger: "floor", replacement: "\\\\lfloor $0 \\\\rfloor $1", options: "mA" },
  { trigger: "mod", replacement: "|$0|$1", options: "mA" },
  { trigger: "lr(", replacement: "\\\\left( $0 \\\\right) $1", options: "mA" },
  { trigger: "lr{", replacement: "\\\\left\\\\{ $0 \\\\right\\\\} $1", options: "mA" },
  { trigger: "lr[", replacement: "\\\\left[ $0 \\\\right] $1", options: "mA" },
  { trigger: "lr|", replacement: "\\\\left| $0 \\\\right| $1", options: "mA" },
  { trigger: "lra", replacement: "\\\\left< $0 \\\\right> $1", options: "mA" },
];
