/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => {
  __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
  return value;
};

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => KingsCalcLatexPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/editor.ts
var import_state = require("@codemirror/state");
var import_view = require("@codemirror/view");
function detectTriggers(docText, from, to) {
  const matches = [];
  const segment = docText.slice(from, to);
  const pattern = /(=|\\approx|\\equiv|@plot2d|@plot3d|@geom|@persist|@convert\s+[A-Za-z°/]+)/g;
  const mathBlocks = [];
  const mathRe = /\$\$?[\s\S]*?\$\$?/g;
  let mm;
  while ((mm = mathRe.exec(segment)) !== null) {
    mathBlocks.push({ start: mm.index, end: mm.index + mm[0].length, content: mm[0] });
  }
  let m;
  while ((m = pattern.exec(segment)) !== null) {
    const triggerText = m[1];
    const triggerIndex = m.index;
    let kind = "evaluate";
    let mode = "exact";
    if (triggerText === "=") {
      kind = "evaluate";
      mode = "exact";
    } else if (triggerText === "\\approx") {
      kind = "evaluate";
      mode = "approximate";
    } else if (triggerText === "\\equiv") {
      kind = "evaluate";
      mode = "simplify";
    } else if (triggerText === "@plot2d") {
      kind = "plot";
      mode = "plot2d";
    } else if (triggerText === "@plot3d") {
      kind = "plot";
      mode = "plot3d";
    } else if (triggerText === "@geom") {
      kind = "plot";
      mode = "geometry";
    } else if (triggerText === "@persist") {
      kind = "persist";
      mode = "persist";
    } else if (triggerText.startsWith("@convert")) {
      kind = "convert";
      mode = triggerText.split(/\s+/)[1];
    }
    let latex = "";
    let mathRange = null;
    const block = mathBlocks.find((b) => triggerIndex >= b.start && triggerIndex < b.end);
    if (block) {
      const localTriggerIndex = triggerIndex - block.start;
      const exprPart = block.content.slice(0, localTriggerIndex);
      latex = stripMathDelimiters(exprPart).trim();
      mathRange = { from: from + block.start, to: from + block.end };
    } else {
      const fullBefore = segment.slice(0, triggerIndex);
      const boundaryMatch = fullBefore.match(/[A-Za-z0-9\\^_{}()+\-*/\s,.<>|]+$/);
      if (boundaryMatch) {
        latex = boundaryMatch[0].trim().replace(/^[-*+]\s+/, "");
      } else {
        latex = fullBefore.trim();
      }
    }
    if (latex && latex.length > 0 && !latex.includes("```")) {
      matches.push({
        kind,
        latex,
        mode,
        fullMatch: triggerText,
        from: from + triggerIndex,
        to: from + triggerIndex + triggerText.length,
        mathRange
      });
    }
  }
  return matches;
}
function stripMathDelimiters(text) {
  return text.replace(/^\$\$?|^\\\(|^\\\[/, "").replace(/\$\$?|\\\)|\\\]$/, "").trim();
}
var ResultWidget = class extends import_view.WidgetType {
  constructor(plugin, trigger) {
    super();
    this.plugin = plugin;
    this.trigger = trigger;
  }
  eq(other) {
    if (!(other instanceof ResultWidget))
      return false;
    return other.trigger.latex === this.trigger.latex && other.trigger.fullMatch === this.trigger.fullMatch && JSON.stringify(other.trigger.mathRange) === JSON.stringify(this.trigger.mathRange);
  }
  toDOM() {
    const container = document.createElement("div");
    container.className = "kct-inline-widget";
    container.style.display = this.trigger.kind === "plot" ? "block" : "inline-block";
    if (this.trigger.kind === "plot") {
      container.classList.add("kct-graph-container");
      container.innerHTML = `<div class="kct-loading">Calculating graph...</div>`;
      void this.renderGraph(container);
    } else {
      container.innerText = " ...";
      void this.resolveEvaluation(container);
    }
    return container;
  }
  async resolveEvaluation(container) {
    try {
      if (this.trigger.kind === "evaluate") {
        const response = await this.plugin.engine.evaluate(this.trigger.latex, this.trigger.mode);
        const result = response.resultLatex || response.resultText || "No result";
        container.innerText = ` ${result}`;
      } else if (this.trigger.kind === "convert") {
        const value = parseFloat(this.trigger.latex);
        if (isNaN(value)) {
          container.innerText = " Invalid number";
          return;
        }
        const response = await this.plugin.engine.convert(value, "unit", this.trigger.mode);
        container.innerText = ` ${response.resultText}`;
      } else if (this.trigger.kind === "persist") {
        const response = await this.plugin.engine.persist(this.trigger.latex);
        container.innerText = response.ok ? ` Stored ${response.storedSymbol}` : " Persist failed";
      }
    } catch (e) {
      container.innerText = " Engine offline";
    }
  }
  async renderGraph(container) {
    try {
      const response = await this.plugin.engine.plot(this.trigger.latex, this.trigger.mode);
      if (response.ok && response.renderHtml) {
        container.innerHTML = "";
        const iframe = document.createElement("iframe");
        iframe.className = "kct-graph-iframe";
        const isDark = document.body.classList.contains("theme-dark");
        const themeClass = isDark ? "theme-dark" : "theme-light";
        iframe.srcdoc = `
          <style>
            body { margin: 0; padding: 0; overflow: hidden; background: transparent; }
            .plotly-graph-div { height: 100vh !important; width: 100vw !important; }
          </style>
          <div class="${themeClass}">${response.renderHtml}</div>
        `;
        container.appendChild(iframe);
        this.plugin.publishInspectorState({
          title: "Kings CalcLatex Graph",
          summary: `Rendering ${this.trigger.mode}`,
          diagnostics: response.diagnostics.map((d) => d.message),
          renderHtml: response.renderHtml,
          latex: this.trigger.latex,
          mode: this.trigger.mode,
          variables: response.variables
        });
      } else {
        container.innerText = " Plot failed";
      }
    } catch (e) {
      container.innerText = " Engine offline";
    }
  }
};
function createInlineRenderer(plugin) {
  const extension = import_state.StateField.define({
    create() {
      return import_view.Decoration.none;
    },
    update(decorations, tr) {
      if (!tr.docChanged && !tr.selection)
        return decorations;
      const builder = new import_state.RangeSetBuilder();
      const doc = tr.state.doc;
      const head = tr.state.selection.main.head;
      const cursorLine = doc.lineAt(head).number;
      for (let i = 1; i <= doc.lines; i++) {
        const line = doc.line(i);
        const matches = detectTriggers(line.text, line.from, line.to);
        for (const match of matches) {
          const targetPos = match.mathRange ? match.mathRange.to : match.to;
          builder.add(
            targetPos,
            targetPos,
            import_view.Decoration.widget({
              side: 1,
              block: match.kind === "plot",
              widget: new ResultWidget(plugin, match)
            })
          );
        }
      }
      return builder.finish();
    },
    provide(f) {
      return import_view.EditorView.decorations.from(f);
    }
  });
  const tabKeymap = import_view.keymap.of([{
    key: "Tab",
    run: (view) => {
      const head = view.state.selection.main.head;
      const line = view.state.doc.lineAt(head);
      const triggers = detectTriggers(line.text, line.from, line.to);
      const match = triggers.find((t) => {
        const atTrigger = Math.abs(t.to - head) <= 1;
        const atMathEnd = t.mathRange && Math.abs(t.mathRange.to - head) <= 1;
        return atTrigger || atMathEnd;
      });
      if (match && (match.kind === "evaluate" || match.kind === "convert")) {
        void (async () => {
          let result = "";
          if (match.kind === "evaluate") {
            const resp = await plugin.engine.evaluate(match.latex, match.mode);
            result = resp.resultLatex || resp.resultText;
          } else {
            const value = parseFloat(match.latex);
            if (!isNaN(value)) {
              const resp = await plugin.engine.convert(value, "unit", match.mode);
              result = resp.resultText;
            }
          }
          if (result) {
            let insertPos = head;
            if (match.mathRange && (head === match.mathRange.to || head === match.mathRange.to - 1)) {
              const text = view.state.doc.sliceString(match.mathRange.from, match.mathRange.to);
              if (text.endsWith("$"))
                insertPos = match.mathRange.to - 1;
              if (text.endsWith("$$"))
                insertPos = match.mathRange.to - 2;
            }
            view.dispatch({
              changes: { from: insertPos, insert: result },
              selection: { anchor: insertPos + result.length }
            });
          }
        })();
        return true;
      }
      return false;
    }
  }]);
  return [extension, import_state.Prec.highest(tabKeymap)];
}

// src/service.ts
var EngineClient = class {
  constructor(baseUrl) {
    this.baseUrl = baseUrl;
  }
  async health() {
    try {
      const response = await fetch(`${this.baseUrl}/health`);
      const data = await response.json();
      return data.ok === true;
    } catch (e) {
      return false;
    }
  }
  async evaluate(latex, mode) {
    const response = await fetch(`${this.baseUrl}/evaluate`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ latex, mode })
    });
    return await response.json();
  }
  async persist(latex) {
    const response = await fetch(`${this.baseUrl}/persist`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ latex })
    });
    return await response.json();
  }
  async plot(latex, mode, ranges, parameters) {
    const response = await fetch(`${this.baseUrl}/plot`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ latex, mode, ranges, parameters })
    });
    return await response.json();
  }
  async convert(value, from_unit, to_unit) {
    const response = await fetch(`${this.baseUrl}/convert`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ value, from_unit, to_unit })
    });
    return await response.json();
  }
};

// src/settings.ts
var import_obsidian = require("obsidian");
var KingsCalcLatexSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "King's CalcLatex Settings" });
    new import_obsidian.Setting(containerEl).setName("Engine Base URL").setDesc("The URL of your local Python math engine.").addText(
      (text) => text.setPlaceholder("http://127.0.0.1:3210/api/v1").setValue(this.plugin.settings.engineBaseUrl).onChange(async (value) => {
        this.plugin.settings.engineBaseUrl = value;
        await this.plugin.saveSettings();
        this.plugin.reconnectEngine();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Completion Key").setDesc("The key to trigger inline evaluation results insertion.").addText(
      (text) => text.setPlaceholder("Tab").setValue(this.plugin.settings.completionKey).onChange(async (value) => {
        this.plugin.settings.completionKey = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/view.ts
var import_obsidian2 = require("obsidian");
var GRAPH_INSPECTOR_VIEW = "kcl-graph-inspector-view";
var GraphInspectorView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    __publicField(this, "state", {
      title: "King's CalcLatex",
      summary: "Inspector is ready.",
      diagnostics: []
    });
  }
  getViewType() {
    return GRAPH_INSPECTOR_VIEW;
  }
  getDisplayText() {
    return "Graph Inspector";
  }
  getIcon() {
    return "presentation";
  }
  async onOpen() {
    this.render();
  }
  setInspectorState(state) {
    this.state = state;
    this.render();
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.classList.add("kct-inspector-container");
    const header = container.createDiv({ cls: "kct-inspector-header" });
    header.createEl("h4", { text: this.state.title });
    header.createEl("p", { text: this.state.summary, cls: "kct-summary" });
    if (this.state.renderHtml) {
      const graphBox = container.createDiv({ cls: "kct-inspector-graph" });
      const iframe = document.createElement("iframe");
      iframe.className = "kct-inspector-iframe";
      const isDark = document.body.classList.contains("theme-dark");
      const themeClass = isDark ? "theme-dark" : "theme-light";
      iframe.srcdoc = `
        <style>
          body { margin: 0; padding: 0; overflow: hidden; background: transparent; }
          .plotly-graph-div { height: 100vh !important; width: 100vw !important; }
        </style>
        <div class="${themeClass}">${this.state.renderHtml}</div>
      `;
      graphBox.appendChild(iframe);
      const controlBox = container.createDiv({ cls: "kct-inspector-advanced-controls" });
      controlBox.createEl("h5", { text: "Bounds" });
      const grid = controlBox.createDiv({ cls: "kct-range-grid" });
      ["x", "y", "z"].forEach((axis) => {
        var _a;
        const row = grid.createDiv({ cls: "kct-range-row" });
        row.createSpan({ text: `${axis}: ` });
        const range = ((_a = this.state.ranges) == null ? void 0 : _a[axis]) || { min: -10, max: 10 };
        const minInput = row.createEl("input", { type: "number", value: range.min.toString() });
        minInput.onchange = (e) => {
          if (!this.state.ranges)
            this.state.ranges = {};
          this.state.ranges[axis] = { min: parseFloat(e.target.value), max: range.max };
        };
        row.createSpan({ text: " to " });
        const maxInput = row.createEl("input", { type: "number", value: range.max.toString() });
        maxInput.onchange = (e) => {
          if (!this.state.ranges)
            this.state.ranges = {};
          this.state.ranges[axis] = { min: range.min, max: parseFloat(e.target.value) };
        };
      });
      if (this.state.variables && this.state.variables.length > 0) {
        controlBox.createEl("h5", { text: "Parameters" });
        this.state.variables.forEach((v) => {
          var _a, _b;
          const row = controlBox.createDiv({ cls: "kct-parameter-row" });
          row.createSpan({ text: `${v}: ` });
          const val = (_b = (_a = this.state.params) == null ? void 0 : _a[v]) != null ? _b : 1;
          const slider = row.createEl("input", { type: "range", value: val.toString() });
          slider.setAttribute("min", "-10");
          slider.setAttribute("max", "10");
          slider.setAttribute("step", "0.1");
          const valLabel = row.createSpan({ text: val.toFixed(1), cls: "kct-slider-value" });
          slider.oninput = (e) => {
            const newVal = parseFloat(e.target.value);
            valLabel.innerText = newVal.toFixed(1);
            if (!this.state.params)
              this.state.params = {};
            this.state.params[v] = newVal;
          };
        });
      }
      const actions = container.createDiv({ cls: "kct-inspector-actions" });
      actions.createEl("button", { text: "Replot", cls: "mod-cta" }).onclick = () => {
        this.plugin.runGraphRefresh(this.state.latex || "", this.state.ranges, this.state.params);
      };
      actions.createEl("button", { text: "Copy LaTeX" }).onclick = () => {
        if (this.state.latex)
          navigator.clipboard.writeText(this.state.latex);
      };
    }
    if (this.state.diagnostics.length > 0) {
      const diagBox = container.createDiv({ cls: "kct-inspector-diagnostics" });
      diagBox.createEl("h5", { text: "Diagnostics" });
      const ul = diagBox.createEl("ul");
      this.state.diagnostics.forEach((d) => ul.createEl("li", { text: d }));
    }
  }
};

// src/main.ts
var DEFAULT_SETTINGS = {
  engineBaseUrl: "http://127.0.0.1:3210/api/v1",
  completionKey: "Tab"
};
var KingsCalcLatexPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    __publicField(this, "settings", DEFAULT_SETTINGS);
    __publicField(this, "engine");
    __publicField(this, "inspectorState", {
      title: "King's CalcLatex",
      summary: "Graph inspector is ready.",
      diagnostics: []
    });
  }
  async onload() {
    await this.loadSettings();
    this.engine = new EngineClient(this.settings.engineBaseUrl);
    this.addSettingTab(new KingsCalcLatexSettingTab(this.app, this));
    this.registerView(
      GRAPH_INSPECTOR_VIEW,
      (leaf) => new GraphInspectorView(leaf, this)
    );
    this.registerEditorExtension([createInlineRenderer(this)]);
    this.addCommand({
      id: "open-graph-inspector",
      name: "Open Graph Inspector",
      callback: async () => {
        await this.activateInspector();
      }
    });
    this.addCommand({
      id: "check-engine-health",
      name: "Check Engine Health",
      callback: async () => {
        const ok = await this.engine.health();
        this.publishInspectorState({
          title: "Engine Health",
          summary: ok ? "Engine is online" : "Engine is offline",
          diagnostics: [ok ? "Successfully reached localhost:3210" : "Could not reach local Python engine."]
        });
      }
    });
  }
  onunload() {
    this.app.workspace.getLeavesOfType(GRAPH_INSPECTOR_VIEW).forEach((leaf) => leaf.detach());
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  reconnectEngine() {
    this.engine = new EngineClient(this.settings.engineBaseUrl);
  }
  async activateInspector() {
    let leaf = this.app.workspace.getLeavesOfType(GRAPH_INSPECTOR_VIEW)[0];
    if (!leaf) {
      leaf = this.app.workspace.getRightLeaf(false);
      await leaf.setViewState({ type: GRAPH_INSPECTOR_VIEW, active: true });
    }
    this.app.workspace.revealLeaf(leaf);
  }
  publishInspectorState(state) {
    this.inspectorState = { ...this.inspectorState, ...state };
    this.app.workspace.getLeavesOfType(GRAPH_INSPECTOR_VIEW).forEach((leaf) => {
      if (leaf.view instanceof GraphInspectorView) {
        leaf.view.setInspectorState(this.inspectorState);
      }
    });
  }
  async runGraphRefresh(latex, ranges, params) {
    const mode = this.inspectorState.mode || "plot2d";
    const response = await this.engine.plot(latex, mode, ranges, params);
    this.publishInspectorState({
      ...this.inspectorState,
      renderHtml: response.renderHtml,
      diagnostics: response.diagnostics.map((d) => d.message),
      ranges: ranges || this.inspectorState.ranges,
      params: params || this.inspectorState.params
    });
  }
};
